name: Backup Firestore

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

env:
  PROJECT_ID: pet-adopt-4150a
  BUCKET_NAME: backup-petadopt-01

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Write service account key
        run: echo '${{ secrets.GCP_SA_KEY }}' > key.json

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: key.json
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Activate service account
        run: gcloud auth activate-service-account --key-file=key.json

      - name: Run Firestore export
        run: gcloud firestore export gs://$BUCKET_NAME
