name: Backup Firestore

on:
  schedule:
    # Chạy mỗi ngày lúc 00:00 UTC (tức 07:00 sáng Việt Nam)
    - cron: "0 0 * * *"
  workflow_dispatch: {}

env:
  PROJECT_ID: pet-adopt-4150a
  BUCKET_NAME: backup-petadopt-01

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Show gcloud info
        run: gcloud info

      - name: Run Firestore export
        run: |
          gcloud firestore export gs://$BUCKET_NAME
