name: Backup Firestore

on:
  schedule:
    - cron: "0 0 * * *"   # Backup lúc 07:00 sáng VN
  workflow_dispatch: {}

env:
  PROJECT_ID: pet-adopt-4150a
  BUCKET_NAME: backup-petadopt-01

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Activate service account
        run: |
          gcloud auth activate-service-account --key-file="$GOOGLE_GHA_CREDS_PATH"

      - name: Show gcloud info
        run: gcloud info

      - name: Run Firestore export
        run: |
          gcloud firestore export gs://$BUCKET_NAME
